### ISSUE TITLE
web address

### ISSUE THREAD

**Issue by vegarringdal** [Wakanda/wakanda-api-reference#7]
why not add link in the readme file?
I actually didnt see any ref to this link at wakanda.org... maybe I missed something ?

https://wakanda.github.io/wakanda-api-reference/docs/globals.html

**Comment by hamzahik** [comment]
This is the entry point for the API reference https://wakanda.github.io/wakanda-api-reference/docs/

It will be referenced by the documentation that is in progress http://wakanda.github.io/wakanda-server-doc/#/doc/overview
